spring:
  datasource:
    url: jdbc:h2:mem:Kfriday
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      encoding: utf-8
      platform: h2
